;;; org-plain-latex-preview.el --- Plain-text Org export with LaTeX-aware cleanup -*- lexical-binding: t; -*-

;;; Commentary:

;; This package defines a small Org export back-end derived from the ASCII
;; back-end.  It is intended for previewing Org documents that are primarily
;; aimed at LaTeX export, while rendering selected LaTeX export directives and
;; house macros in a more readable plain-text form.
;;
;; It does not attempt to run LaTeX or fully interpret TeX.  Instead, it
;; translates common structural directives such as \smallskip and samepage
;; markers into plain-text equivalents, while dropping LaTeX header material.

;; To enable:
;; (require 'org-plain-latex-preview)

;; -OR-

;; (use-package org-plain-latex-preview
;;   :ensure nil)

;;; Code:

(require 'ox)
(require 'ox-ascii)
(require 'subr-x)

(defgroup org-plain-latex-preview nil
  "Plain-text preview of LaTeX-oriented Org documents."
  :group 'org-export)

(defcustom org-plain-latex-preview-width 52
  "Text width used by `org-plain-latex-preview'.

This value is bound to `org-ascii-text-width' during export.
It should generally correspond to the line length produced by the
intended print pipeline."
  :type 'integer
  :group 'org-plain-latex-preview)

;; NOTE: This overlaps conceptually with `org-macro-displays', but
;; serves a different purpose: export output rather than buffer
;; display.
;; TODO: Convert to a `defcustom' if package growth justifies
;; user-configurable macro substitutions.
(defvar org-plain-latex-preview-macro-alist
  '(("\\td{}"     . "...")
    ("\\fd{}"     . ".....")
    ("\\longdash{}" . "---------")
    ("\\first{}" . "(1st)")
    ("\\second{}" . "(2nd)")
    ("\\third{}" . "(3rd)"))
  "Alist mapping LaTeX macros to plain-text replacements.")

(defun org-plain-latex-preview--replace-macros (string)
  "Replace known LaTeX macros in STRING."
  (dolist (pair org-plain-latex-preview-macro-alist string)
    (setq string
          (replace-regexp-in-string
           (regexp-quote (car pair))
           (cdr pair)
           string t t))))

(defun org-plain-latex-preview--latex-directive (value)
  "Return a plain-text rendering of LaTeX directive VALUE."
  (pcase (string-trim value)
    ("\\smallskip" "\n")
    ("\\medskip" "\n\n")
    ("\\bigskip" "\n\n")
    ("\\asterism" "* * *\n\n")
    ("\\begin{samepage}" "")
    ("\\end{samepage}" "")
    ((or "\\clearpage" "\\newpage" "\\pagebreak") "\n\n\n\n")
    (_ "")))

(defun org-plain-latex-preview-keyword (keyword _contents _info)
  "Render Org KEYWORD for plain LaTeX-aware preview export."
  (let ((key (org-element-property :key keyword))
        (value (or (org-element-property :value keyword) "")))
    (pcase key
      ("LATEX" (org-plain-latex-preview--latex-directive value))
      ("LATEX_HEADER" "")
      ("LATEX_HEADER_EXTRA" "")
      ("OPTIONS" "")
      ("BIND" "")
      (_ nil))))

(defun org-plain-latex-preview-latex-fragment (fragment _contents _info)
  "Render LaTeX FRAGMENT as readable plain text."
  (org-plain-latex-preview--replace-macros
   (string-trim
    (org-element-property :value fragment))))

(defun org-plain-latex-preview-latex-environment (environment _contents _info)
  "Render LaTeX ENVIRONMENT for plain-text preview."
  (let ((value (org-element-property :value environment)))
    (cond
     ((string-match-p "\\\\begin{samepage}" value) "")
     (t ""))))

;; Suppress the ASCII title block when both #+TITLE: and #+AUTHOR: are
;; explicitly blank. This mirrors LaTeX export behaviour. The title
;; block is generated by `org-ascii-inner-template', not
;; `org-ascii-template'.
(defun org-plain-latex-preview--blank-keyword-p (info key)
  "Return non-nil if KEY is present in INFO parse tree with a blank value."
  (let ((tree (plist-get info :parse-tree))
        found)
    (org-element-map tree 'keyword
      (lambda (kw)
        (let ((k (org-element-property :key kw))
              (v (org-element-property :value kw)))
          (when (string= k key)
            (setq found
                  (string-empty-p
                   (string-trim (or v "")))))))
      info)
    found))

(defun org-plain-latex-preview--blank-title-block-p (info)
  "Return non-nil if TITLE and AUTHOR are explicitly blank."
  (and (org-plain-latex-preview--blank-keyword-p info "TITLE")
       (org-plain-latex-preview--blank-keyword-p info "AUTHOR")))

(defun org-plain-latex-preview-template (contents info)
  "Final cleanup for plain LaTeX preview export."
  (if (org-plain-latex-preview--blank-title-block-p info)
      (string-trim-left contents)
    (org-ascii-template contents info)))

(defun org-plain-latex-preview-inner-template (contents info)
  "Render CONTENTS without ASCII title block when TITLE and AUTHOR are blank."
  (if (org-plain-latex-preview--blank-title-block-p info)
      contents
    (org-ascii-inner-template contents info)))

(org-export-define-derived-backend 'plain-latex-preview 'ascii
  :menu-entry
  '(?p "Preview Plain Text"
       ((?p "To temporary buffer"
            (lambda (a s v b)
              (let ((org-ascii-text-width org-plain-latex-preview-width))
                (org-export-to-buffer 'plain-latex-preview
                    "*Org Plain LaTeX Preview*"
                  a s v b nil
                  (lambda ()
                    (text-mode)
                    (run-at-time
                     0 nil
                     (lambda (buf)
                       (when-let* ((win (get-buffer-window buf)))
                         (select-window win)
                         (delete-other-windows)))
                     (current-buffer)))))))
        (?P "To file"
            (lambda (a s v b)
              (let ((org-ascii-text-width org-plain-latex-preview-width))
                (org-export-to-file 'plain-latex-preview
                    (org-export-output-file-name ".txt" s)
                  a s v b))))))
  :translate-alist
  '((inner-template . org-plain-latex-preview-inner-template)
    (template . org-plain-latex-preview-template)
    (keyword . org-plain-latex-preview-keyword)
    (latex-fragment . org-plain-latex-preview-latex-fragment)
    (latex-environment . org-plain-latex-preview-latex-environment)))

(provide 'org-plain-latex-preview)
;;; org-plain-latex-preview.el ends here

; LocalWords:  asterism samepage clearpage newpage pagebreak
